CU-8685u1cq8_Council-add-DoWhile-runner
chain-ml/council pull request #94
Opened 2023-09-29 14:39 UTC by Naccomy

2023-09-29 14:39 UTC, aflament commented
Task linked: [CU-8685u1cq8 [Council] add DoWhile runner](https://app.clickup.com/t/8685u1cq8)

2023-09-29 16:37 UTC, gkoch78 requested changes
Let great overall. 
I'd like to see on more test about the predicate throwing :)

2023-10-02 14:56 UTC, Naccomy commented on council/runners/do_while_runner.py
> +    """
```suggestion
    """
    Runner that executes one time and then while the given predicates returns `True`.
    """
```

2023-10-02 14:57 UTC, Naccomy commented on council/runners/do_while_runner.py
> +            runner: a runner to be executed while the predicate returns `True`
```suggestion
            runner: a runner to be executed one time and then while the predicate returns `True`
```

2023-10-02 17:34 UTC, gkoch78 commented on council/runners/do_while_runner.py
> +    Runner that executes while the given predicate returns `True`
```suggestion
    Runner that executes an inner Runner while the given predicate returns `True`. The predicate is executed at the end of loop. As such, the inner runner executes at least once.
```

2023-10-02 17:35 UTC, gkoch78 requested changes
please add to the class diagram here: https://council--94.org.readthedocs.build/en/94/reference/runners/do_while.html

2023-10-03 17:11 UTC, gkoch78 approved these changes
🚀

2023-10-03 17:24 UTC, merged